name: Setup Python dev
description: Setup a Python development environment with Poetry and Tox
inputs:
  python-version:
    description: Python version to use
    required: false
    default: "3.10"
outputs:
  project-version:
    description: Version of the checked-out Poetry project
    value: ${{ steps.project-version.outputs.version }}
runs:
  using: composite
  steps:
    - name: Install python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ inputs.python-version }}
    - name: Install poetry & tox
      run: |
        python -m pip install -U pip
        pip install poetry tox
    - id: project-version
      name: Extract Poetry project version
      run: echo "::set-output name=version::$(poetry version | awk '{print $2}')"
      shell: bash
