jobs:
  - job: pypi
    pool:
      vmImage: ubuntu-18.04
    steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: 3.9
          addToPath: true
        displayName: Install Python
      - script: |
          set -e
          python -m pip install -U pip
          pip install poetry
        displayName: Prepare environment
      - script: |
          set -e
          poetry build
        displayName: Build Python dist
      - task: CopyFiles@2
        inputs:
          sourceFolder: $(System.DefaultWorkingDirectory)/dist
          targetFolder: $(Build.ArtifactStagingDirectory)
        displayName: Prepare Python dist for artifacts
      - task: PublishPipelineArtifact@1
        inputs:
          path: $(Build.ArtifactStagingDirectory)
          artifact: python-dist
        displayName: Publish Python dist to artifacts

  - job: release_changelog
    pool:
      vmImage: ubuntu-18.04
    steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: 3.9
          addToPath: true
        displayName: Install Python
      - script: |
          set -e
          python -m pip install -U pip
          pip install poetry
        displayName: Prepare environment
      - script: |
          set -e
          version=`poetry version | awk '{print $2}'`
          echo "Version is: $version"
          python utils/extract_changelog.py $version > $(Build.ArtifactStagingDirectory)/release_$version.md
        displayName: Generate release changelog
      - task: PublishPipelineArtifact@1
        inputs:
          path: $(Build.ArtifactStagingDirectory)
          artifact: changelog
        displayName: Publish release changelog to artifacts
