trigger:
  branches:
    exclude:
      - "*"
  tags:
    include:
      - "v3.*"

pr: none

stages:
  - stage: tests
    jobs:
      - template: templates/integration-jobs.yml
  - stage: package
    jobs:
      - template: templates/packaging-jobs.yml
  - stage: release
    jobs:
      - template: templates/releasing-jobs.yml
