name: Main Pipeline

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-20.04, macos-11, windows-2022]
        python: ["3.7", "3.10"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - run: |
          python -m pip install -U pip
          pip install poetry tox
      - run: |
          tox -e py
